apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nr137826u-python
  janus-idp.io/tekton: nr137826u-python
  backstage.io/kubernetes-id: nr137826u-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nr137826u-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
